services:
  - type: web
    name: librolibre
    runtime: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "librolibre-2.onrender.com,librolibre.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://librolibre-2.onrender.com,https://librolibre.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: librolibre-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    staticFiles:
      - path: /static
        destination: staticfiles

databases:
  - name: librolibre-db
    databaseName: librolibre
    user: librolibre
    plan: free
    region: oregon
    pgMajorVersion: 15